#!/bin/bash

# get the json data
curl -X GET "LINK"  > /root/results.json

# get current ISO time
mongo --eval "ISODate()" > /root/date.txt

# remove unnecesarry info from ISO call
sed -i '1,4d' /root/date.txt

# open the json to add more data
truncate -s-2 /root/results.json

# get the current date and put in variable
DATE=$(cat /root/date.txt)

# add ISO time and close back the json
sed -i '1 s|$|,"Creation_Time":|' /root/results.json
sed -i '1 s|$|'"$DATE"'|' /root/results.json
sed -i '1 s|$|}]|' /root/results.json

# push the new data to MongoDB
mongoimport --db admin --collection price --file /root/results.json --jsonArray
